apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-webui
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-webui
  template:
    metadata:
      labels:
        app: ollama-webui
    spec:
      containers:
        - name: ollama-webui
          image: ghcr.io/ollama/open-webui:main
          env:
            - name: OLLAMA_API_BASE_URL
              value: "http://ollama:11434/api"
          volumeMounts:
            - mountPath: /app/backend/data
              name: webui-storage
          ports:
            - containerPort: 8080
      volumes:
        - name: webui-storage
          persistentVolumeClaim:
            claimName: ollama-webui-pvc
      restartPolicy: Always
