apiVersion: v1
kind: Service
metadata:
  name: ollama-webui
  namespace: ollama
spec:
  selector:
    app: ollama-webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - port: 8080
      targetPort: 8080
